[package]
name = "cmdreporter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.28.1", optional = true }
ratatui = "0.28.1"
color-eyre = "0.6.2"